spring.application.name=taskManager

spring.data.mongodb.uri=${MONGODB_URI}

spring.data.mongodb.database = taskmanagerdb

spring.data.mongodb.auto-index-creation=true

spring.main.allow-circular-references=true

server.servlet.context-path=/task-manager